/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RequisitionLinkParamsSerializer.
    /// </summary>
    [DataContract(Name = "RequisitionLinkParams")]
    public partial class RequisitionLinkParams : IEquatable<RequisitionLinkParams>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequisitionLinkParams" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequisitionLinkParams() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequisitionLinkParams" /> class.
        /// </summary>
        /// <param name="aspspId">ASPSP ID. Should match one used while creating EUA, if it&#39;s linked to this requisition (required).</param>
        public RequisitionLinkParams(string aspspId = default(string))
        {
            // to ensure "aspspId" is required (not null)
            if (aspspId == null) {
                throw new ArgumentNullException("aspspId is a required property for RequisitionLinkParams and cannot be null");
            }
            this.AspspId = aspspId;
        }

        /// <summary>
        /// ASPSP ID. Should match one used while creating EUA, if it&#39;s linked to this requisition
        /// </summary>
        /// <value>ASPSP ID. Should match one used while creating EUA, if it&#39;s linked to this requisition</value>
        [DataMember(Name = "aspsp_id", IsRequired = true, EmitDefaultValue = false)]
        public string AspspId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RequisitionLinkParams {\n");
            sb.Append("  AspspId: ").Append(AspspId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequisitionLinkParams);
        }

        /// <summary>
        /// Returns true if RequisitionLinkParams instances are equal
        /// </summary>
        /// <param name="input">Instance of RequisitionLinkParams to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequisitionLinkParams input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AspspId == input.AspspId ||
                    (this.AspspId != null &&
                    this.AspspId.Equals(input.AspspId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AspspId != null)
                {
                    hashCode = (hashCode * 59) + this.AspspId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
