/*
 * Nordigen Account Information Services API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Status1c5Enum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status1c5Enum
    {
        /// <summary>
        /// Enum CRlongCREATEDdescriptionRequisitionHasBeenSuccessfullyCreated for value: {\&quot;short\&quot;:\&quot;CR\&quot;,\&quot;long\&quot;:\&quot;CREATED\&quot;,\&quot;description\&quot;:\&quot;Requisition has been successfully created\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"CR\",\"long\":\"CREATED\",\"description\":\"Requisition has been successfully created\"}")]
        CRlongCREATEDdescriptionRequisitionHasBeenSuccessfullyCreated = 1,

        /// <summary>
        /// Enum LNlongLINKEDdescriptionAccountHasBeenSuccessfullyLinkedToRequisition for value: {\&quot;short\&quot;:\&quot;LN\&quot;,\&quot;long\&quot;:\&quot;LINKED\&quot;,\&quot;description\&quot;:\&quot;Account has been successfully linked to requisition\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"LN\",\"long\":\"LINKED\",\"description\":\"Account has been successfully linked to requisition\"}")]
        LNlongLINKEDdescriptionAccountHasBeenSuccessfullyLinkedToRequisition = 2,

        /// <summary>
        /// Enum EXlongEXPIREDdescriptionAccessToAccountHasExpiredAsSetInEndUserAgreement for value: {\&quot;short\&quot;:\&quot;EX\&quot;,\&quot;long\&quot;:\&quot;EXPIRED\&quot;,\&quot;description\&quot;:\&quot;Access to account has expired as set in End User Agreement\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"EX\",\"long\":\"EXPIRED\",\"description\":\"Access to account has expired as set in End User Agreement\"}")]
        EXlongEXPIREDdescriptionAccessToAccountHasExpiredAsSetInEndUserAgreement = 3,

        /// <summary>
        /// Enum RJlongREJECTEDdescriptionSSNVerificationHasFailed for value: {\&quot;short\&quot;:\&quot;RJ\&quot;,\&quot;long\&quot;:\&quot;REJECTED\&quot;,\&quot;description\&quot;:\&quot;SSN verification has failed\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"RJ\",\"long\":\"REJECTED\",\"description\":\"SSN verification has failed\"}")]
        RJlongREJECTEDdescriptionSSNVerificationHasFailed = 4,

        /// <summary>
        /// Enum UAlongUNDERGOINGAUTHENTICATIONdescriptionEndUserIsRedirectedToTheFinancialInstitutionForAuthentication for value: {\&quot;short\&quot;:\&quot;UA\&quot;,\&quot;long\&quot;:\&quot;UNDERGOING_AUTHENTICATION\&quot;,\&quot;description\&quot;:\&quot;End-user is redirected to the financial institution for authentication\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"UA\",\"long\":\"UNDERGOING_AUTHENTICATION\",\"description\":\"End-user is redirected to the financial institution for authentication\"}")]
        UAlongUNDERGOINGAUTHENTICATIONdescriptionEndUserIsRedirectedToTheFinancialInstitutionForAuthentication = 5,

        /// <summary>
        /// Enum GAlongGRANTINGACCESSdescriptionEndUserIsGrantingAccessToTheirAccountInformation for value: {\&quot;short\&quot;:\&quot;GA\&quot;,\&quot;long\&quot;:\&quot;GRANTING_ACCESS\&quot;,\&quot;description\&quot;:\&quot;End-user is granting access to their account information\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"GA\",\"long\":\"GRANTING_ACCESS\",\"description\":\"End-user is granting access to their account information\"}")]
        GAlongGRANTINGACCESSdescriptionEndUserIsGrantingAccessToTheirAccountInformation = 6,

        /// <summary>
        /// Enum SAlongSELECTINGACCOUNTSdescriptionEndUserIsSelectingAccounts for value: {\&quot;short\&quot;:\&quot;SA\&quot;,\&quot;long\&quot;:\&quot;SELECTING_ACCOUNTS\&quot;,\&quot;description\&quot;:\&quot;End-user is selecting accounts\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"SA\",\"long\":\"SELECTING_ACCOUNTS\",\"description\":\"End-user is selecting accounts\"}")]
        SAlongSELECTINGACCOUNTSdescriptionEndUserIsSelectingAccounts = 7,

        /// <summary>
        /// Enum GClongGIVINGCONSENTdescriptionEndUserIsGivingConsentAtNordigensConsentScreen for value: {\&quot;short\&quot;:\&quot;GC\&quot;,\&quot;long\&quot;:\&quot;GIVING_CONSENT\&quot;,\&quot;description\&quot;:\&quot;End-user is giving consent at Nordigen&#39;s consent screen\&quot;}
        /// </summary>
        [EnumMember(Value = "{\"short\":\"GC\",\"long\":\"GIVING_CONSENT\",\"description\":\"End-user is giving consent at Nordigen's consent screen\"}")]
        GClongGIVINGCONSENTdescriptionEndUserIsGivingConsentAtNordigensConsentScreen = 8

    }

}
